version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13
    working_directory: ~/nhs-info-app
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm ci
      - save_cache:
        - paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
        name: Lint
        command: npm run lint
      - run:
        name: Test
        command: npm run coverage
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build